---
version: '3.0'

services:
  envoy:
    build:
      context: envoy/
    ports:
      - '3000:3000'
      - '9901:9901'
    environment:
      - ARIO_HOST=ario
      - ARIO_PORT=4000
      - ARWEAVE_GATEWAY=arweave.net
      - LOG_LEVEL=info

  ario:
    build:
      context: .
    ports:
      - 4000:4000
    volumes:
      - ./data:/app/data
    environment:
      ENV: development
