---
version: '3.0'

services:
  envoy:
    image: ghcr.io/ar-io/ar-io-envoy:latest
    build:
      context: envoy/
    ports:
      - '3000:3000'
      - '9901:9901'
    environment:
      - LOG_LEVEL=info
      - TVAL_AR_IO_HOST=core
      - TVAL_AR_IO_PORT=4000
      - TVAL_GATEWAY_HOST=${TRUSTED_GATEWAY_HOST:-arweave.net}
      - TVAL_GRAPHQL_HOST=${GRAPHQL_HOST:-core}
      - TVAL_GRAPHQL_PORT=${GRAPHQL_PORT:-4000}

  core:
    image: ghcr.io/ar-io/ar-io-core:latest
    build:
      context: .
    ports:
      - 4000:4000
    volumes:
      - ./data:/app/data
    environment:
      - ENV=${ENV:-development}
      - TRUSTED_NODE_URL=${TRUSTED_NODE_URL:-https://arweave.net}
      - TRUSTED_GATEWAY_URL=https://${TRUSTED_GATEWAY_HOST:-arweave.net}
      - START_HEIGHT=${START_HEIGHT:-0}
      - STOP_HEIGHT=${STOP_HEIGHT:-Infinity}
      - SKIP_CACHE=${SKIP_CACHE:-false}
      - SIMULATED_REQUEST_FAILURE_RATE=${SIMULATED_REQUEST_FAILURE_RATE:-0}
