---
version: '3.0'

services:
  envoy:
    image: ghcr.io/ar-io/ar-io-envoy:latest
    build:
      context: envoy/
    ports:
      - '3000:3000'
      - '9901:9901'
    environment:
      - ARIO_HOST=ar-io-core
      - ARIO_PORT=4000
      - ARWEAVE_GATEWAY=arweave.net
      - LOG_LEVEL=info

  ar-io-core:
    image: ghcr.io/ar-io/ar-io-core:latest
    build:
      context: .
    ports:
      - 4000:4000
    volumes:
      - ./data:/app/data
    environment:
      ENV: development
