name: Build AR.IO Envoy container image

on:
  push:
    branches:
      - main
    paths:
      - 'envoy/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # Setup
      - uses: actions/checkout@v3

      # Build and push container image (only on main)
      - name: Log in to the GitHub Container Registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push container image
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v3
        with:
          file: envoy/Dockerfile
          push: true
          tags: |
            ghcr.io/ar-io/ar-io-envoy:latest
            ghcr.io/ar-io/ar-io-envoy:${{ github.sha }}

      # Success notification
      - name: Send Slack success notification
        if: success()
        env:
          SLACK_TITLE: Build succeeded!
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        uses: rtCamp/action-slack-notify@v2

      # Failure notification
      - name: Send Slack failure notification
        if: failure()
        env:
          SLACK_TITLE: Build failed!
          SLACK_COLOR: danger
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        uses: rtCamp/action-slack-notify@v2
